version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"       # API REST
      - "2575:2575"       # MLLP default port (HL7)
    environment:
      - HF_DATABASE_URL=postgresql+asyncpg://healthflow:healthflow@postgres:5432/healthflow
      - HF_NATS_URL=nats://nats:4222
      - HF_REDIS_URL=redis://redis:6379
      - HF_AWS_REGION=${HF_AWS_REGION:-us-east-1}
      - HF_AWS_ACCESS_KEY_ID=${HF_AWS_ACCESS_KEY_ID}
      - HF_AWS_SECRET_ACCESS_KEY=${HF_AWS_SECRET_ACCESS_KEY}
      - HF_OTEL_ENDPOINT=http://otel-collector:4317
    depends_on:
      - postgres
      - nats
      - redis
    volumes:
      - ./backend:/app/backend

  postgres:
    image: timescale/timescaledb:latest-pg16
    environment:
      POSTGRES_DB: healthflow
      POSTGRES_USER: healthflow
      POSTGRES_PASSWORD: healthflow
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/home/postgres/pgdata/data

  nats:
    image: nats:latest
    command: ["--jetstream", "--store_dir", "/data"]
    ports:
      - "4222:4222"     # Client
      - "8222:8222"     # HTTP monitoring
    volumes:
      - natsdata:/data

  redis:
    image: redis:7-alpine
    ports:
      - "6380:6379"

  # Observability
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    ports:
      - "4317:4317"     # gRPC
      - "4318:4318"     # HTTP
      - "8889:8889"     # Prometheus metrics
    volumes:
      - ./infra/otel-collector-config.yml:/etc/otelcol-contrib/config.yaml
    depends_on:
      - tempo

  tempo:
    image: grafana/tempo:2.6.1
    command: ["-config.file=/etc/tempo.yml"]
    ports:
      - "3200:3200"     # Tempo API
    volumes:
      - ./infra/tempo.yml:/etc/tempo.yml
      - tempodata:/var/tempo

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./infra/grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - tempo
      - otel-collector

volumes:
  pgdata:
  natsdata:
  tempodata:
