apiVersion: v1
kind: Secret
metadata:
  name: healthflow-secrets
  namespace: healthflow
type: Opaque
stringData:
  HF_AWS_ACCESS_KEY_ID: ""      # Fill in deployment
  HF_AWS_SECRET_ACCESS_KEY: ""  # Fill in deployment
  HF_AWS_REGION: "us-east-1"
